### ISSUE TITLE
version numbers are wrong for the week between uplift and release

### ISSUE THREAD

**Issue by lonnen** [luser/whatthetrain#10]
Since beta is uplifts a week early, the source files will list master and beta as having the same version number for the week prior to a release. Maybe product-details is a better source of this information.

**Comment by luser** [comment]
Right now whatthetrain has no server component, so if you can find an API to get this info that'd be great.

**Comment by lonnen** [comment]
I have an idea for such a service but no resources with which to build it just yet. Maybe in a month or two.

**Comment by lonnen** [comment]
We could also detect this specific, known failure case and hardcode a workaround. Way easier.

**Comment by lonnen** [comment]
Or patch the FF release process. whatever floats your boat

**Comment by luser** [comment]
Detect if beta == release and just subtract one from release in that case? That is hacky and would probably be fine.
