### ISSUE TITLE
Column design

### ISSUE THREAD

**Issue by ryanfeeley** [luser/whatthetrain#11]
A little messing around with the inspector and I was able to get to:
![what-train-is-it](https://cloud.githubusercontent.com/assets/68213/6452092/41a827f0-c101-11e4-81be-4ce0fdd24266.png)

Do you think something like this could work?

**Comment by luser** [comment]
I like it! My only quibble is that the version numbers and branch names
are not very prominent. If you can figure out how to make them a bit
bigger it'd be great.

**Comment by ryanfeeley** [comment]
![screenshot 2015-03-02 17 38 35](https://cloud.githubusercontent.com/assets/68213/6452332/0091ec4a-c103-11e4-9e85-4e82160a9362.png)

**Comment by luser** [comment]
Sold!

**Comment by luser** [comment]
Did you want to submit this in the form of a pull request? There's not much to the style sheet: https://github.com/luser/whatthetrain/blob/master/style.css and the JS that creates the elements is here:
https://github.com/luser/whatthetrain/blob/master/trains.js#L43

**Comment by ryanfeeley** [comment]
Sorry, I just firebugged it and didn't save the code. I never actually had this running on my machine.

**Comment by luser** [comment]
Bummer! My CSS skills are approximately zero, so I wouldn't know where to start.
