### ISSUE TITLE
No release version displayed

### ISSUE THREAD

**Issue by hwine** [luser/whatthetrain#13]
As of right now, no release version is displayed. The 38.0 & spring release (38.0.5) are "special" and may not match the usual assumptions. Hopefully we'll never do this again, but maybe a link to the wiki would be a good "default" value

**Comment by luser** [comment]
No, this is just a dumb bug, fallout from https://github.com/luser/whatthetrain/commit/78adde5e27c6c385349359f223b8e98dc6566dc6 . (That's what I get for hacking on code when I'm tired!)

**Comment by luser** [comment]
Deployed that fix, looks ok on whattrainisitnow.com . Thanks for the bug report!

**Comment by hwine** [comment]
That's the advantage of having the page in the kiosk rotation at the offices! Thanks for quick fix!
