### ISSUE TITLE
Add columns and change font

### ISSUE THREAD

**Issue by ryanfeeley** [luser/whatthetrain#15]
Just a suggestion, and not sure if you have the data to do this, but I kept thinking about the concept of train. Font is Fira Sans, weight 200.

Would something like this work better? (again, Firebugged, code not kept)

<img width="1398" alt="what-train-is-it-now" src="https://cloud.githubusercontent.com/assets/68213/8686918/95311d94-2a3f-11e5-9f78-57948e2473a8.png">

**Comment by luser** [comment]
We'd have to fake the data, probably, since I don't have a way to query for past and future releases. The concept is clever, but I don't think it adds a lot of value, honestly.

**Comment by ryanfeeley** [comment]
Yeah, it's not revolutionary work by any stretch.

I do think it fails the fill the office screens nicely.

![2015-07-13 08 43 07](https://cloud.githubusercontent.com/assets/68213/8730148/07bb3b82-2ba4-11e5-9b34-388620afcda4.jpg)

Just the font changes here alone improve that. Font is Fira Sans, weight 200. H1 is around 500%.

**Comment by luser** [comment]
If you want to try out hacking the CSS you can just click "Edit" on style.css and edit it in-browser:
https://github.com/luser/whatthetrain/blob/gh-pages/style.css

**Comment by luser** [comment]
I think potch's changes a while back effectively fixed this:
https://github.com/luser/whatthetrain/commit/3e3cd5706801131043df10291bfa2f9fa21f892b
