### ISSUE TITLE
Wrong stable version on http://whattrainisitnow.com/

### ISSUE THREAD

**Issue by sylvestre** [luser/whatthetrain#16]
Currently, http://whattrainisitnow.com/ is showing 39.0.2 as a stable release.

Issue: 39.0.2 never shipped, it was a fennec only build done for a partner. It hasn't ship and won't.

**Comment by luser** [comment]
The site just pulls the milestone.txt file from each branch repo:
https://hg.mozilla.org/releases/mozilla-release/raw-file/default/config/milestone.txt

Until someone builds me a web service to get the actual released Firefox version that's the best I can do right now. Sorry!

**Comment by luser** [comment]
At some point this data came into existence: https://product-details.mozilla.org/1.0/firefox_versions.json

We could just fetch that one file which has all the versions we need!

**Comment by luser** [comment]
I believe https://github.com/luser/whatthetrain/commit/4d3060fd73a3ffa785e619ca997a44d415c250d3 will have fixed this by pulling the release version from the product-details file.
