### ISSUE TITLE
No distinction between android and desktop

### ISSUE THREAD

**Issue by sylvestre** [luser/whatthetrain#17]
Currently the stable version is marked as 39.0.2.

We never built a 39.0.2 for Desktop. This was a Mobile only build (which didn't ship).
For stable release, we should differentiate Desktop & Mobile as it is common that they don't ship at the same time.

**Comment by luser** [comment]
I don't know that this is _super_ useful, but if we had the data we could probably figure out a way to display it when the releases diverge.

**Comment by luser** [comment]
I'm guessing https://github.com/luser/whatthetrain/commit/4d3060fd73a3ffa785e619ca997a44d415c250d3 fixed this by making us only display desktop versions. I don't think displaying separate Android versions is useful enough to worry about.
