### ISSUE TITLE
Add ESR version number?

### ISSUE THREAD

**Issue by Qeole** [luser/whatthetrain#18]
Just a thought about a possible enhancement: could it be worth adding the number of current ESR (_Extended Support Release_) version? (Right now it is Fx 38.3.0esr)

I do not know where we could fetch it exactly, though. Current milestone is at https://hg.mozilla.org/releases/mozilla-esr38/raw-file/default/config/milestone.txt, but this requires knowing the `38` number; new ESR seems to be out every 7 “standard” versions, so we could probably compute the `38` depending on current release version (`current_ESR == current_release - (current_release + 4) % 7`), but this might be hazardous.

@luser: what's your opinion about it?

**Comment by luser** [comment]
That sounds very useful, but we would need a stable place to fetch the latest ESR from.

**Comment by Qeole** [comment]
I don't know any :-(. I'll come back here if I ever find one.

**Comment by luser** [comment]
As I just said in #16, I found out today that this exists: https://product-details.mozilla.org/1.0/firefox_versions.json . It has the ESR version in it, so we could use that.

**Comment by Qeole** [comment]
Yep, sounds great! I had never seen that page either.

If you do switch source, I can take this issue, adding ESR should be easy once #16 is fixed. I don't reckon there is any particular logo for ESR?
