### ISSUE TITLE
Release label is doubled in the page

### ISSUE THREAD

**Issue by hossainalikram** [luser/whatthetrain#19]
The error is like below:

![aa](https://cloud.githubusercontent.com/assets/8605491/23557011/b9824312-0058-11e7-9695-9ac32beadedb.PNG)

If it needs to be edited manually edited, I wish to do that, If i am directed that way.

**Comment by Qeole** [comment]
Never seen that, and can't reproduce in my browser (Fx 52 on Linux).

@hossainalikram Do you have more details? Like what OS / what browser you use? Is the error still present if you try again now and reload the page? Does this happen only for the “release” item, or for all elements of the train?

**Comment by luser** [comment]
It definitely doesn't look like that for me on Firefox Nightly or Edge on Windows 10.

**Comment by kjozwiak** [comment]
I ran into the same issue that was mentioned above and managed to reproduce it several times using the following STR (note: this isn't 100% and may take several tries):

* load https://www.mozilla.org/en-US/ in a new tab, however it can be any website
* load http://whattrainisitnow.com/ in the same tab
* click on "Fork me on Github"
* now go back and forth between the websites using the Back/Forward buttons and you'll notice that you'll run into the issue (might take 20-30 seconds of going back and forth)

Platform/Build being used:

* macOS 10.12.3 x64
* https://archive.mozilla.org/pub/firefox/nightly/2017/03/2017-03-10-09-01-16-mozilla-central/

<img width="1281" alt="screen shot 2017-03-10 at 5 11 50 pm" src="https://cloud.githubusercontent.com/assets/2602313/23815486/7e8f9cb0-05b6-11e7-85a6-33e676cec0ba.png">

**Comment by luser** [comment]
I was able to reproduce this the other day, but I can no longer reproduce it. I suspect either the changes in https://github.com/luser/whatthetrain/pull/22 or my followup in https://github.com/luser/whatthetrain/commit/15b929fddb6e625669481dcfc16420be53931fb4 fixed this.

Please feel free to reopen if you're still able to reproduce this!
