### ISSUE TITLE
Host using HTTPS

### ISSUE THREAD

**Issue by edmorley** [luser/whatthetrain#21]
A blocker for preloading HSTS on mozilla.io is switching http://corsica.mozilla.io/ to HTTPS, however it can't switch until the various sites it displays support HTTPS too, otherwise there will be mixed content warnings.

$ curl -I https://whattrainisitnow.com
curl: (51) SSL: no alternative certificate subject name matches target host name 'whattrainisitnow.com'

https://bugzilla.mozilla.org/show_bug.cgi?id=1137035
https://github.com/mozilla/corsica/issues/51#issuecomment-291249386

**Comment by luser** [comment]
It's currently hosted on GitHub pages. It sounds like the only way to make SSL work is to [run everything through CloudFlare](https://hackernoon.com/set-up-ssl-on-github-pages-with-custom-domains-for-free-a576bdf51bc). That seems doable, I'll just have to find time to set that up.

**Comment by potch** [comment]
It's annoying (but I grok why) that SSL is free if you just use .github.io, but otherwise requires hoops to make HTTPS.

**Comment by luser** [comment]
I configured cloudflare and switched my DNS over to it, so hopefully when that all propagates https://whattrainisitnow.com/ should work. I'll leave this open until we verify it works.

**Comment by luser** [comment]
Hooray! It works!

**Comment by edmorley** [comment]
Many thanks!
