### ISSUE TITLE
Proposal:  addon with button, for the extra lazy

### ISSUE THREAD

**Issue by gregglind** [luser/whatthetrain#25]
Proposed:  webExtension with a 'badged button'. 
- clicking the button goes here.
- hoving on the button has the main 4 info batches here.

Thoughts, suggestions, and  welcome.

**Comment by luser** [comment]
I'm pretty unlikely to do any of that, but feel free to take whatever you need from this repo if you're interested in doing so! It's actually pretty simple nowadays, we're just pulling all the info from [firefox_versions.json](https://product-details.mozilla.org/1.0/firefox_versions.json).

**Comment by luser** [comment]
If someone wanted to do this they certainly could but I don't think this is really a feature request for this site specifically.
