### ISSUE TITLE
Update to new Developer Edition icon

### ISSUE THREAD

**Issue by luser** [luser/whatthetrain#29]
There's [a new Developer Edition icon](https://dxr.mozilla.org/mozilla-central/source/browser/branding/aurora). We should use it.

@pascalchevrel where did you get the Nightly icon you added? The devedition icons in the branding directory aren't the same size as the icons we have in this repo.

**Comment by pascalchevrel** [comment]
I I remember correctly, shortlander sent me a high res png for the nightly icon

**Comment by potch** [comment]
https://bits.potch.me/FirefoxRelease.png
https://bits.potch.me/FirefoxDeveloperEdition.png
https://bits.potch.me/FirefoxNightly.png

/me floats away on a dandelion wisp

**Comment by potch** [comment]
If you wouldn't mind, use large-size graphics so the office tvs get nice crisp logos <3

**Comment by luser** [comment]
@potch thanks! Don't suppose there's an equivalent to the release-icon-with-beta-ribbon floating around? https://github.com/luser/whatthetrain/blob/gh-pages/images/beta.png

**Comment by luser** [comment]
[The channels page](https://www.mozilla.org/en-US/firefox/channel/desktop/) has this image:
https://www.mozilla.org/media/img/logos/firefox/beta-logo.90b7d81fba2e.png

If you can dredge up an equivalent resolution of that I would love to use it!

**Comment by luser** [comment]
OK, in the interim I'm just using the release icon for beta so that things don't look janky. Also I'm not good at CSS, so I used `background-size: 120px` to scale the high-res images so they look similar to the previous presentation. Happy to take PRs to do that in a better way. @potch: I added you as a collaborator so if you source a beta image you can just commit it. Thanks!
