### ISSUE TITLE
Please update logos [early 2019]

### ISSUE THREAD

**Issue by hildjj** [luser/whatthetrain#33]
Current logos available here: https://mozilla.design/firefox/logos-usage/

In a perfect world, these would be tied to the release number, so that the ESR logo would be correct for the release number at the time.  In the meantime, could someone please look up the 68 logo, and use that for ESR?

**Comment by chelsea-lewis** [comment]
@hildjj Confirmed with Stephen Horlander that 68.4.1 ESR is using the old logo and does not need to be updated at this time.

**Comment by luser** [comment]
I'm unlikely to get around to this anytime soon but I'm happy to merge a PR.
