### ISSUE TITLE
HSTS

### ISSUE THREAD

**Issue by annevk** [luser/whatthetrain#36]
It seems this site still supports a non-HTTPS version which I don't think is needed anymore with modern GitHub Pages.

**Comment by luser** [comment]
When I first set this all up GitHub Pages didn't support HTTPS with custom domains so I configured CloudFlare to serve HTTPS for it. I could change that all but I'm trying to get Mozilla to take ownership of this. :) See [bug 1642255](https://bugzilla.mozilla.org/show_bug.cgi?id=1642255) and [bug 1642254](https://bugzilla.mozilla.org/show_bug.cgi?id=1642254).

**Comment by annevk** [comment]
Fair enough!
