### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by sagudev** [luser/whatthetrain#37]
It would be good if website supported dark mode

**Comment by lonnen** [comment]
Thank you for the issue!

I'm deprecating this project in favor of [fx-trains](https://fx-trains.herokuapp.com/). The domain will continue to function, but it will serve fx-trains instead. I'm going to close this issue out as part of deprecating and archiving this project.

you can read more here:
https://github.com/mozilla/whatthetrain/issues/38#issuecomment-1300868596
