### ISSUE TITLE
Calendar integration seems broken

### ISSUE THREAD

**Issue by freshstrangemusic** [luser/whatthetrain#38]
This used to show the next merge / soft freeze date, but does not any longer.

**Comment by moztcampbell** [comment]
That data can be found on the fx-trains app https://fx-trains.herokuapp.com/ if you need it. (It seems that fx-trains should be replacing what-train-is-it-now entirely in the future)

**Comment by luser** [comment]
> It seems that fx-trains should be replacing what-train-is-it-now entirely in the future

n.b. I transferred ownership of https://whattrainisitnow.com/ to @lonnen a while back, so you should be able to point that hostname at the new site.

**Comment by lonnen** [comment]
@moztcampbell I own the domain personally for some reason. I'm happy to point it over at fx-trains and decomm what the train whenever

**Comment by Dexterp37** [comment]
> @moztcampbell I own the domain personally for some reason. I'm happy to point it over at fx-trains and decomm what the train whenever

This would really be great, as folks are referencing to http://whattrainisitnow.com/ in quite a few places (and might not be aware of https://fx-trains.herokuapp.com/ )

**Comment by pascalchevrel** [comment]
@lonnen Hi, I am the owner of the fx-trains.herokuapp.com app, would you agree to have whattrainisitnow.com point to it? Thanks!

**Comment by lonnen** [comment]
@pascalchevrel Sure thing. Follow the steps [here](https://devcenter.heroku.com/articles/custom-domains#add-a-custom-root-domain) and let me know the DNS target. I'll get the ALIAS created as soon as I get the notice. We don't have a ton of overlap in our hours but you can try me on slack for a faster response

**Comment by lonnen** [comment]
The domain records now point to heroku DNS, and with @pascalchevrel's help this domain is now configured to serve fx-trains with ssl. I'm still waiting for DNS to propagate to my machine but I'll start deprecating this project and pointing people over there!

Thanks everyone!
